permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: runge
  email: wangrun20088002@126.cm
  link: http://www.wangrun.club
  github: http://github.com/lubiao2012

# 站点信息
title: runge的博客 
description: runge的博客
url: http://www.wangrun.club
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://image.baidu.com/search/detail?ct=503316480&z=0&ipn=d&word=%E7%A7%91%E6%AF%94&pn=3&spn=0&di=3938650240&pi=&rn=1&tn=baiduimagedetail&istype=&ie=utf-8&oe=utf-8&in=3354&cl=2&lm=-1&st=&cs=2819165425%2C3105419965&os=2815624736%2C634064731&simid=0%2C0&adpicid=0&ln=1000&fmq=1378374347070_R&ic=0&s=0&se=&sme=&tab=&face=&ist=&jit=&statnum=star&cg=&bdtype=11&objurl=http%3A%2F%2Fy3.ifengimg.com%2Fa%2F2015_49%2Fd4f286d033d82c3.jpg&fromurl=ippr_z2C%24qAzdH3FAzdH3Ffr56pf_z%26e3Btujg2_z%26e3Bv54AzdH3FwAzdH3Fda8c8da9AzdH3F9mc80cm8_a_z%26e3Bfip4s&gsm=3c
favicon: http://image.baidu.com/search/detail?ct=503316480&z=0&ipn=d&word=%E7%A7%91%E6%AF%94&pn=3&spn=0&di=3938650240&pi=&rn=1&tn=baiduimagedetail&istype=&ie=utf-8&oe=utf-8&in=3354&cl=2&lm=-1&st=&cs=2819165425%2C3105419965&os=2815624736%2C634064731&simid=0%2C0&adpicid=0&ln=1000&fmq=1378374347070_R&ic=0&s=0&se=&sme=&tab=&face=&ist=&jit=&statnum=star&cg=&bdtype=11&objurl=http%3A%2F%2Fy3.ifengimg.com%2Fa%2F2015_49%2Fd4f286d033d82c3.jpg&fromurl=ippr_z2C%24qAzdH3FAzdH3Ffr56pf_z%26e3Btujg2_z%26e3Bv54AzdH3FwAzdH3Fda8c8da9AzdH3F9mc80cm8_a_z%26e3Bfip4s&gsm=3c

# google analytics 设置
ga:
  id: UA-54767140-1
  url: www.wangrun.club

# disqus 设置
disqus:
  shortname: wangrun-zh
